### ISSUE TITLE
I had a PR merged, but it wasn't counted in the contest

### ISSUE THREAD

**Issue by mathdevelop** [globocom/hacktoberfest#31]
Instead of having a review and getting approved, my PR was merged directly, which resulted in my contribution not being counted, and I didn't qualify for the prize. Can you help me?

PR: https://github.com/globocom/megadraft/pull/437

Thank you, see you later!

**Comment by mathdevelop** [comment]
The same thing happened in my other PR: https://github.com/globocom/megadraft/pull/436

**Comment by RaphaelVRossi** [comment]
hey @mathdevelop 

Thank's for your all contribution.

As You can see here, your contribution was counted!

![image](https://github.com/globocom/hacktoberfest/assets/19207341/ce91b337-bea0-4f3b-b544-e2122970fd4f)

You can check [here too](https://hacktoberfest.globo.com/participantes/)

**Comment by lettalves** [comment]
It seems that it counted the first one, it should take just a little while, I was the one who got anxious, sorry for the inconvenience.

Thank you very much, see you later!!

**Comment by mathdevelop** [comment]
It seems that it counted the first one, it should take just a little while, I was the one who got anxious, sorry for the inconvenience.

Thank you very much, see you later!!
